### ISSUE TITLE
Upgrades typically fail & require manual restart

### ISSUE THREAD

**Issue by bland328** [macexx/EAP-Controller#11]
EAP-Controller works brilliantly for me, so thanks for that. However, when I deploy a new version of EAP-Controller, startup typically (or perhaps always?) fails like this:

```
*** Running /etc/my_init.d/01_start.sh...
Upgrading local packages(Security) - This might take awhile(first run takes some extra time)
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Upgrade Done....
Starting Omada Controller. Please wait...............................................................................................................................................................................................................................................................................................................

Start failed.
```

Curiously, though even multiple "cold" starts will fail like this, if I intervene and do a `docker restart`, the results of the warm restart are different, starting after the upgrade calculation:

```
...
Calculating upgrade...
The following packages will be upgraded:
libpam-modules libpam-modules-bin libpam-runtime libpam0g
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
...
```

After that, everything progresses nicely, and EAP-Controller behaves perfectly until the next time I upgrade the container.

**Comment by macexx** [comment]
Sry, almost forgot that I have this image(just been rolling along).

Yes, this have been an issue since the start. (for me also just haven't cared).

Cant say this is your issue but most likely.

Guess you are running the container privileged/host? and not forwarding (the quite extensive port list) as bridged.

The issue is every time EAP starts up it checks every port to see if its not in use(no idea rly about the proccess since it´s baked in to the java) or it wont start.

Well so when you run it as host network the ports will still stay open for some time after the container is killed, so running it as  bridged and forwarding the port seems like the only option. (has worked great for me)

No idea if there is an docker option to force close the ports/proccesses but that would be a great option.

**Comment by macexx** [comment]
This was an temp file issue(phusion baseimage(java version) in this case), cant remember really which file it was.
But fixed itself since the image does an upgrade of packages in the start.

A friend had the exact same issue on a nas(trying to build a plugin) think it was qnap where java saved a temp file to /opt/tmp instead of /tmp so Omada or rather "java" in this case thought ports where in use on a reboot since there still was an old temp file.

Might be useful info for someone in the future.
